import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Nunito } from "next/font/google";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/store/ReduxProvider";
import { getDictionary } from "./dictionaries";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vision Things",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
  const dict = await getDictionary(lang);
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={lang === "ar" ? { direction: "rtl" } : { direction: "ltr" }}
      >
        <ReduxProvider>
          <Navbar dict={dict} lang={lang} />
          {children}
          <Footer dict={dict} lang={lang} />
        </ReduxProvider>
      </body>
    </html>
  );
}
